# Generated by Django 3.0.6 on 2020-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
